# Generated by Django 4.2.1 on 2023-06-04 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0002_comment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trip', to='countries_app.country'),
        ),
    ]
