# Generated by Django 4.2.1 on 2023-06-04 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0003_alter_trip_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='private_coment',
            new_name='private_comment',
        ),
    ]
