# Generated by Django 4.2.1 on 2023-06-06 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('countries_app', '0004_rename_private_coment_trip_private_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='countries_app.trip'),
        ),
    ]
